export type { GitFileStatus, GitFileStat } from "./types"
export type { ParsedGitStatusPorcelainLine } from "./parse-status-porcelain-line"
export { parseGitStatusPorcelainLine } from "./parse-status-porcelain-line"
export { parseGitStatusPorcelain } from "./parse-status-porcelain"
export { parseGitDiffNumstat } from "./parse-diff-numstat"
export { collectGitDiffStats } from "./collect-git-diff-stats"
export { formatFileChanges } from "./format-file-changes"

export { createAgentWorktree } from "./create-agent-worktree"
export type { AgentWorktreeInfo } from "./create-agent-worktree"
export { removeAgentWorktree } from "./remove-agent-worktree"
export { resolveRepoRoot } from "./repo-root-resolver"
export { resolveBaseRef } from "./base-ref-resolver"
export { sanitizeRefComponent } from "./sanitize-ref-component"
export { runGit, runGitOrThrow, tryRunGit } from "./run-git"
export type { RunGitOptions, RunGitResult } from "./run-git"

export { listGitWorktrees, findWorktreePathForBranch } from "./worktree-list"
export type { ListedWorktree } from "./worktree-list"
